
---
version: '3.7'
services:
  mattermost-bot :
    image: local/bot
    container_name: mattermost-bot
    restart: always
    networks:
      - botnetwork
    ports:
      - "80:8080"

  cleverserver:
    image: local/cleverserver
    container_name: cleverserver
    restart: always
    networks:
      - botnetwork

    ports:
      - "8090:8090"


networks:
  botnetwork:
    external:
      name: botnetwork
  default:
    driver: bridge



