name: 'Terraform'

on:
  push:
    branches:
      - master
  pull_request:
  
jobs:
 terraform:
    name: 'Terraform'
    runs-on: self-hosted
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Getting Statefile from static directory
      run: cp /actions-runner/terraform.tfstate* .
      if: always()
      
    - name: Setting API Secret
      run: sed -in s/SECRETAPI/${{ secrets.API }}/g docker/mattermost-bots/src/main/resources/application.properties
      
    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: Terraform destroy
      run: terraform destroy -auto-approve -input=false
  
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      
    - name: Saving Statefile to static directory
      run: cp terraform.tfstate* /actions-runner/  
      if: always()
