name: 'Terraform'

on:
  push:
    branches:
      - master
  pull_request:
  
jobs:
 terraform:
    name: 'Terraform'
    runs-on: self-hosted
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setting up terraform credentials
      run: export OS_CLOUD=openstack
    - name: Checking terraform credentials
      run: cat ~/.config/openstack/clouds.yaml && env | grep OS_CLOUD
    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: Terraform Plan
      id: plan
      #if: github.event_name == 'pull_request'
      run: terraform plan -no-color -input=false
      continue-on-error: true
